# Generated by Django 3.1.3 on 2020-11-27 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='home_type',
            field=models.CharField(choices=[('Maison', 'Maison'), ('Appartement', 'Appartement'), ('Villa', 'Villa')], default='Maison', max_length=50),
        ),
        migrations.AlterField(
            model_name='listing',
            name='sale_type',
            field=models.CharField(choices=[('A vendre', 'A Vendre'), ('A louer', 'A Louer')], default='A vendre', max_length=50),
        ),
    ]
